/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 84d68d87b2245b3f63aa01931b49a949)
interface __BaseEnv_Env {
  BOOK_CATALOG_SOURCE: 'rakuten'
  RAKUTEN_APPLICATION_URL: 'https://shoka.yuto-urashima24.workers.dev'
  RAKUTEN_APPLICATION_ID: string
  RAKUTEN_ACCESS_KEY: string
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/api/index')
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'BOOK_CATALOG_SOURCE'
      | 'RAKUTEN_APPLICATION_URL'
      | 'RAKUTEN_APPLICATION_ID'
      | 'RAKUTEN_ACCESS_KEY'
    >
  > {}
}
